"""add

Revision ID: 1394da0fa19
Revises: 3783f5f4718
Create Date: 2016-08-27 19:58:10.902689

"""

# revision identifiers, used by Alembic.
revision = '1394da0fa19'
down_revision = '3783f5f4718'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
