"""add_teams

Revision ID: 14a610aa6fc
Revises: 1394da0fa19
Create Date: 2016-08-27 20:56:03.864561

"""

# revision identifiers, used by Alembic.
revision = '14a610aa6fc'
down_revision = '1394da0fa19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('add_teams', sa.Unicode(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'add_teams')
    ### end Alembic commands ###
