"""initial

Revision ID: 20caadbfe7d
Revises: None
Create Date: 2016-08-26 23:39:45.452684

"""

# revision identifiers, used by Alembic.
revision = '20caadbfe7d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('email', sa.Unicode(), nullable=True),
    sa.Column('department1', sa.Unicode(), nullable=True),
    sa.Column('department2', sa.Unicode(), nullable=True),
    sa.Column('skill', sa.UnicodeText(), nullable=True),
    sa.Column('reason', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    ### end Alembic commands ###
