"""add_mysql_2

Revision ID: 3783f5f4718
Revises: 448b1ec35e5
Create Date: 2016-08-27 19:30:29.068248

"""

# revision identifiers, used by Alembic.
revision = '3783f5f4718'
down_revision = '448b1ec35e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
