"""add_teams

Revision ID: 38489daea06
Revises: 14a610aa6fc
Create Date: 2016-08-27 20:58:06.689382

"""

# revision identifiers, used by Alembic.
revision = '38489daea06'
down_revision = '14a610aa6fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
