"""add

Revision ID: 4ddd083b987
Revises: 1e92265475e
Create Date: 2016-08-27 14:57:09.836115

"""

# revision identifiers, used by Alembic.
revision = '4ddd083b987'
down_revision = '1e92265475e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
